/*
Copyright 2015, James J. Hayes

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA.
*/

"use strict";

/*
 * This module provides a placeholder for methods that replace bare spell names
 * on character sheets with longer descriptions.  To use, pass a set of rules
 * to the spellRules method, e.g.,
 *
 *    SRD35SpellDescriptions.spellRules(SRD35.rules);
 *
 */
function SRD35SpellDescriptions() {
}

SRD35SpellDescriptions.descriptions = {
  "Acid Arrow": "R$RL' Ranged touch 2d4 HP/rd for ${1 + Math.floor(lvl/3)} rd",
  "Acid Fog": "R$RM' 20' fog cylinder 2d6 HP/rd for $L rd",
  "Acid Splash": "R$RS' Ranged touch 1d3 HP",
  "Aid": "Touched +1 attack/fear saves, +1d8+$Lmin10 HP for $L min",
  "Air Walk": "Touched walks on air for $L10 min",
  "Alarm": "R$RS' 20' radius alarmed for $L2 hr",
  "Align Weapon": "Touched weapon Will save or gains alignment for $L min",
  "Alter Self": "Self becomes small (+2 Dex) or medium (+2 Str) humanoid for $L min",
  "Analyze Dweomer": "R$RS' Target Will save or reveals magical aspects for $L rd",
  "Animal Growth": "R$RM' Animal target Fort save or double in size for $L min",
  "Animal Messenger": "R$RS' Tiny animal target goes to specified place for $L dy",
  "Animal Shapes": "R$RS' $L allies in 30' area become chosen animal for $L hr",
  "Animal Trance": "R$RS' 2d6 HD animals Will save or facinated for conc",
  "Animate Dead": "Touched corpses become $L2 HD of skeletons/zombies",
  "Animate Objects": "R$RM' $L objects attack foes for $L rd",
  "Animate Plants": "R$RS' $Ldiv3 plants attack/entwine foes for $L rd/hr",
  "Animate Rope": "R$RM' ${50 + 5 * lvl}' rope obey for $L rd",
  "Antilife Shell": "10'-radius bars living for $L min",
  "Antimagic Field": "10'-radius suppresses magic for $L10 min",
  "Antipathy": "Named kind/align creatures Will save or avoid $L10' cube for $L2 hr",
  "Antiplant Shell": "10'-radius bars animate plants for $L min",
  "Arcane Eye": "Invisible remote eye moves 30' for $L min",
  "Arcane Lock": "Magical lock on door/portal/chest open DC +10 with lock/20 otherwise",
  "Arcane Mark": "Permanent in/visible personal rune on object/creature",
  "Arcane Sight": "R120' See auras/spell abilities for $L min, DC 15+level to know school",
  "Astral Projection": "Projects you and others to Astral Plane",
  "Atonement": "Restore alignment/holy powers",
  "Augury": "${Math.min(70 + lvl, 90)}% chance to know weal/woe of act proposed w/in 30 min",
  "Awaken": "Animal/tree target gains human sentience",
  "Baleful Polymorph": "R$RS' Target Fort save or become 1HD creature, Will save to keep abilities",
  "Bane": "Enemies w/in 50' Will save or -1 attack/fear saves $L min",
  "Banishment": "R$RS' $L2 HD extraplanar creatures Will save or banished from plane",
  "Barkskin": "+$BarkskinAC natural armor for $L10 min",
  "Bear's Endurance": "Touched +4 Con for $L min",
  "Beast Shape I": "Become small (+2 Dex/+1 AC) or medium (+2 Str/+2 AC) animal for $L min",
  "Beast Shape II": "Become tiny (+4 Dex/-2 Str/+1 AC) or large (+4 Str/-2 Dex/+4 AC) animal for $L min",
  "Beast Shape III": "Become dimunitive (+6 Dex/-4 Str/+1 AC) or huge (+6 Str/-4 Dex/+6 AC) animal or small (+4 Dex/+2 AC) or medium (+4 Str/+4 AC) magical beast for $L min",
  "Beast Shape IV": "Become tiny (+8 Dex/-2 Str/+3 AC) or large (+6 Str/-2 Dex/+2 Con/+6 AC) magical beast for $L min",
  "Bestow Curse": "Touched Will save or permanent -6 ability, -4 attack/saves/checks, or 50% chance/rd of losing action",
  "Binding": "R$RS' Target Will save (min $Ldiv2 HD) or magically imprisoned",
  "Black Tentacles": "R$RM' Tentacles grapple (CMB/CMD ${lvl + 5}/${lvl + 15}) 20' radius, 1d6+4/rd HP for $L rd",
  "Blade Barrier": "R$RM' Blade wall ${Lmin15}d6 HP (Ref half) for $L min",
  "Blasphemy": "Nonevil creatures w/in 40' with equal/-1/-5/-10 HD Will save or dazed 1 rd/-2d6 Str (save half) 2d4 rd/paralyzed 1d10 min (save 1 rd)/killed (save 3d6+$Lmin25 HP)",
  "Bleed": "R$RS' Stabilized target Will save or resume dying",
  "Bless": "R50' Allies +1 attack/fear saves for $L min",
  "Bless Water": "Makes 1 pint holy water",
  "Bless Weapon": "Weapon good aligned, +1 vs. evil foe DR for $L min",
  "Blight": "Touched plant ${Lmin15}d6 HP, Fort half",
  "Blindness/Deafness": "R$RM' target Fort save or permanently blind or deaf",
  "Blink": "Randomly cross material/ethereal planes for $L rd, foes 50% miss chance, half HP from area attacks/falling",
  "Blur": "Foes 20% miss chance for $L min",
  "Break Enchantment": "R$RS' $L targets freed from enchantments/transmutations/curses",
  "Breath Of Life": "Heal 5d8+$L/max 25 plus resurrect target dead lt 1 rd",
  "Bull's Strength": "Touched +4 Str for $L min",
  "Burning Hands": "R15' cone ${Lmin5}d4 HP (Ref half)",
  "Call Lightning": "R$RM' $L bolts 3d6 HP (Ref half), 1/rd for $L min",
  "Call Lightning Storm": "R$RL' 15 bolts 5d6 HP (Ref half), 1/rd for $L min",
  "Calm Animals": "R$RS' 2d4+$L HD of animals Will save or docile for $L min",
  "Calm Emotions": "R$RM' Creatures in 20' radius Will save or pacified $L rd/conc",
  "Cat's Grace": "Touched +4 Dex for $L min",
  "Cause Fear": "R$RS' Target le 5 HD flee for 1d4 rd (Will shaken 1 rd)",
  "Chain Lightning": "R$RL' ${Lmin20}d6 HP primary/$Lmin20 secondary targets (Ref half, secondary save at +2)",
  "Changestaff": "Staff becomes treant-like creature for $L hr",
  "Chaos Hammer": "R$RM' Lawful in 20'-radius burst ${Math.min(Math.floor(source/2),5)}d8 HP and slowed 1d6 rd, neutral half (Will half)",
  "Charm Animal": "R$RS' Target Will save or treats you as trusted friend for $L hr",
  "Charm Monster": "R$RS' Target Will save or treats you as trusted friend for $L dy",
  "Charm Person": "R$RS' Target Will save or treats you as trusted friend for $L hr",
  "Chill Metal": "R$RS' Metal of $Ldiv2 creatures Will save or 0/1/2/2/2/1/0d4 HP for 7 rd",
  "Chill Touch": "$L touched Will save or 1d6 HP negative energy, Fort save or 1 Str (undead flee 1d4+$L rd instead)",
  "Circle Of Death": "R$RM' ${Lmin20}d4 HD of creatures le 8 HD in 40' Fort save or die",
  "Clairaudience/Clairvoyance": "$RL' Remote sight or hearing for $L min",
  "Clenched Fist": "R$RM' 10' (AC 20, caster HP) hand cover (+4 AC), move 60', hit (+$L+mod for 1d8+11, Fort save or stunned 1 rd), bull rush (CMB ${lvl + 12}) for $L rd",
  "Cloak Of Chaos": "$L targets in 20' +4 AC/saves and SR 25 and mental protection vs. lawful, lawful hits cause Will save or confused 1 rd for $L rd",
  "Clone": "Soul enters duplicate if original dies",
  "Cloudkill": "R$RM' 20' cylinder moves away 10', 1-3 HD die, 4-6 HD die (Fort 1d4 Con), 6+ HD 1d4 Con (Fort half) for $L min",
  "Color Spray": "R15' cone Targets with 2/4/any HD Will save or unconscious 2d4 rd/blind 1d4 rd/stunned 1 rd",
  "Command": "R$RS' Target Will save or approach/drop/fall/flee/halt for 1 rd",
  "Command Plants": "R$RS' $L2 HD plant creatures Will save or obey for $L dy",
  "Command Undead": "R$RS' Undead target Will save or obey for $L dy",
  "Commune": "Deity answers $L yes/no questions",
  "Commune With Nature": "Learn natural facts for $L mi outdoors/$L100' underground",
  "Comprehend Languages": "Self understands all languages for $L10 min",
  "Cone Of Cold": "R60' cone ${Lmin15}d6 HP (Ref half)",
  "Confusion": "R$RM' Creatures in 15' radius Will save or randomly normal/babble/d8+str to self/attack nearest for $L rd",
  "Consecrate": "R$RS' Positive energy in 20' radius gives undead -1 attack/damage/saves for $L2 hr",
  "Contact Other Plane": "Ask $Ldiv2 questions of extraplanar entity",
  "Contagion": "Touched Fort save or diseased",
  "Contingency": "Set trigger for ${Math.min(Math.floor(source / 3), 6)}-level spell for $L dy",
  "Continual Flame": "Touched emits heatless torch flame permanently",
  "Control Plants": "R$RS' $L2 HD plant creatures Will save or obey for $L min",
  "Control Undead": "R$RS' Undead target Will save or obey for $L min",
  "Control Water": "R$RL' Raise/lower ${Math.pow(source, 3)} 10'x10'x2' of water $L2' for $L10 min",
  "Control Weather": "Create seasonal weather in 2 mi radius for 4d12 hr",
  "Control Winds": "R$L40' Changes wind direction/speed in $L40'x40' cylinder for $L10 min",
  "Corrupt Weapon": "Weapon evil aligned, +1 vs. good foe DR for $L min",
  "Create Food And Water": "Daily food/water for $L3 humans/$L horses",
  "Create Undead": "Raise ghoul/ghast/mummy/mohrg from physical remains at level -/12/15/18",
  "Create Greater Undead": "Raise shadow/wraith/spectr/devourer from physical remains at level -/16/18/20",
  "Create Water": "R$RS' Creates $L2 gallons of pure water",
  "Creeping Doom": "R${Math.min(25 + 5 * Math.floor(source / 2), 100)}' Four 60-HP insect swarms 4d6 HP obey for $L rd",
  "Crushing Despair": "R30' cone Targets Will save or -2 attack/damage/saves/checks for $L min",
  "Crushing Hand": "R$RM' 10' (AC 20, caster HP) hand cover (+4 AC), move 60', grapple (CMB ${lvl + 12}, 2d6+12 HP) for $L rd",
  "Cure Critical Wounds": "Touched heal/damage undead 4d8+$Lmin20 (Will half)",
  "Cure Light Wounds": "Touched heal/damage undead 1d8+$Lmin5 (Will half)",
  "Cure Minor Wounds": "Touched heal 1 HP",
  "Cure Moderate Wounds": "Touched heal/damage undead 2d8+$Lmin10 (Will half)",
  "Cure Serious Wounds": "Touched heal/damage undead 3d8+$Lmin15 (Will half)",
  "Curse Water": "Makes 1 pint unholy water",
  "Dancing Lights": "R$RM' 4 torch lights in 10' radius move 100' for 1 min",
  "Darkness": "Touched lowers illumination one step in 20'-radius for $L min",
  "Darkvision": "Touched sees 60' in total darkness for $L hr",
  "Daylight": "Touched radiates 60'-radius illumination for $L10 min",
  "Daze": "R$RS' Humanoid target le 4 HD Will save or lose next action",
  "Daze Monster": "R$RM' Creature target le 6 HD Will save or lose next action",
  "Death Knell": "Touched w/negative HP Will save or die and you gain 1d8 HP/+2 Str/+1 caster level for 10*target HD min",
  "Death Ward": "Touched +4 vs. death spells/effects, immune drain for $L min",
  "Deathwatch": "R30' cone Reveals state of targets for $L10 min",
  "Deep Slumber": "R$RS' 10 HD of targets Will save or sleep $L min",
  "Deeper Darkness": "Touched lowers illumination two steps in 60'-radius for $L10 min",
  "Delay Poison": "Touched immune to poison for $L hr",
  "Delayed Blast Fireball": "R$RL' ${Lmin20}d6 HP (Ref half) in 20' radius, delay le 5 rd",
  "Demand": "25-word message to target, Will save or carry out suggestion",
  "Desecrate": "R$RS' Negative energy in 20' radius gives undead +1 attack/damage/saves/HP per HD for $L2 hr",
  "Destruction": "R$RS' Target $L10 HP, consumed if slain (Fort 10d6 HP)",
  "Detect Animals Or Plants": "R$RL' cone info on animals/plants for $L10 min",
  "Detect Chaos": "R60' cone info on chaotic auras for $L10 min",
  "Detect Evil": "R60' cone info on evil auras for $L10 min",
  "Detect Good": "R60' cone info on good auras for $L10 min",
  "Detect Law": "R60' cone info on lawful auras for $L10 min",
  "Detect Magic": "R60' cone info on magical auras for $L min",
  "Detect Poison": "R$RS' Detects poison in target, DC20 Wis/Alchemy check for type",
  "Detect Scrying": "R40' Detects scrying, opposed caster check to see source",
  "Detect Secret Doors": "R60' cone info on secret doors for $L min",
  "Detect Snares And Pits": "R60' cone info on traps $L10 min",
  "Detect Thoughts": "R60' cone info on thoughts for $L min",
  "Detect Undead": "R60' cone info on undead auras for $L min",
  "Dictum": "R40' Nonlawful creatures with equal/-1/-5/-10 HD Will save or deafened 1d4 rd/staggered 2d4 rd (save 1d4)/paralyzed 1d10 min (save 1 rd)/killed (save 3d6+$Lmin25 HP)",
  "Dimension Door": "Teleports self and touched willing object/creature $RL'",
  "Dimensional Anchor": "R$RM' Ranged touch bars extradimensional travel for $L min",
  "Dimensional Lock": "R$RM' Bar extradimensional travel in 20' radius for $L dy",
  "Diminish Plants": "Prunes/blights growth of normal plants",
  "Discern Lies": "R$RS' Reveals lies from $L creatures for $L rd/conc",
  "Discern Location": "Know exact location of creature/object",
  "Disguise Self": "Self change appearance/+10 disguise for $L10 min",
  "Disintegrate": "R$RM' Target ${Math.min(lvl*2,40)}d6 HP (Fort half), dust if slain",
  "Dismissal": "R$RS' Target Will save or returned to native plane",
  "Dispel Chaos": "Touched +4 AC vs. chaotic/touch to dismiss chaotic creature/spell",
  "Dispel Evil": "Touched +4 AC vs. evil/touch to dismiss evil creature/spell",
  "Dispel Good": "Touched +4 AC vs. good/touch to dismiss good creature/spell",
  "Dispel Law": "Touched +4 AC vs. lawful/touch to dismiss lawful creature/spell",
  "Dispel Magic": "R$RM' d20+$L vs. 11+caster level cancels spell/effect",
  "Displacement": "Attacks on touched 50% miss for $L rd",
  "Disrupt Undead": "R$RS' Ranged touched undead 1d6 HP",
  "Disrupting Weapon": "Undead hit w/touched weapon Will save or destroyed for $L rd",
  "Divination": "${Math.min(70 + lvl, 90)}% chance for advice on act proposed w/in a week",
  "Divine Favor": "Self +${Math.min(Math.floor(lvl/3),3)} attack/damage for 1 min",
  "Divine Power": "Self +${Math.min(Math.floor(lvl/3),6)} attack/damage/Str check, +$L HP for $L rd",
  "Dominate Animal": "R$RS' Target Will save or obey thoughts for $L rd",
  "Dominate Monster": "R$RS' Target Will save or obey thoughts for $L dy",
  "Dominate Person": "R$RS' Target Will save or obey thoughts for $L dy",
  "Doom": "R$RM' Target will save or shaken (-2 attack/damage/saves/checks) for $L min",
  "Dream": "Touched sends message to sleeping target",
  "Eagle's Splendor": "Touched +4 Cha for $L min",
  "Earthquake": "R$RL Intense tremor shakes 80' radius for 1 rd",
  "Elemental Body I": "Become small air (+2 Dex/+2 AC/fly 60'/whirlwind), earth (+2 Str/+4 AC/earth glide), fire (+2 Dex/+2 AC/resist fire/burn), water (+2 Con/+4 AC/swim 60'/vortex/breathe water) elemental, 60' darkvision for $L min",
  "Elemental Body II": "Become medium air (+4 Dex/+3 AC/fly 60'/whirlwind), earth (+4 Str/+5 AC/earth glide), fire (+4 Dex/+3 AC/resist fire/burn), water (+4 Con/+5 AC/swim 60'/vortex/breathe water) elemental, 60' darkvision for $L min",
  "Elemental Body III": "Become large air (+2 Str/+4 Dex/+4 AC/fly 60'/whirlwind), earth (+6 Str/-2 Dex/+2 Con/+6 AC/earth glide), fire (+4 Dex/+2 Con/+4 AC/resist fire/burn), water (+2 Str/-2 Dex/+6 Con/+6 AC/swim 60'/vortex/breathe water) elemental, 60' darkvision/immune bleed, critical, sneak attack for $L min",
  "Elemental Body IV": "Become huge air (+4 Str/+6 Dex/+4 AC/fly 120'/whirlwind), earth (+8 Str/-2 Dex/+4 Con/+6 AC/earth glide), fire (+6 Dex/+4 Con/+4 AC/resist fire/burn), water (+4 Str/-2 Dex/+8 Con/+6 AC/swim 120'/vortex/breathe water) elemental, 60' darkvision/immune bleed, critical, sneak attack/DR 5/- for $L min",
  "Elemental Swarm": "R$RM' Summons 2d4 large, then 1d4 huge, then 1 greater  elementals for $L10 min",
  "Endure Elements": "Touched comfortable in at -50-140F for 1 dy",
  "Energy Drain": "R$RS' Ranged touch 2d4 negative levels for 1 dy, Fort save or permanent (undead +2d4x5 HP for 1 hr)",
  "Enervation": "R$RS' Ranged touch 1d4 negative levels for $L hr (undead +1d4x5 HP for 1 hr)",
  "Enlarge Person": "R$RS' Target humanoid Fort save or double size (+2 Str/-2 Dex/-1 attack/-1 AC) for $L min",
  "Entangle": "R$RL' Creatures in 40' radius Ref save or entangled for $L min",
  "Enthrall": "R$RM' Listeners Will save or captivated for 1 hr",
  "Entropic Shield": "Foes' ranged attacks 20% miss for $L min",
  "Erase": "R$RS' Two pages of writing vanish (magical writing DC 15 caster check)",
  "Ethereal Jaunt": "Self ethereal for $L rd",
  "Etherealness": "Self+$Ldiv3 others ethereal for $L min",
  "Expeditious Retreat": "Self speed +30 for $L min",
  "Explosive Runes": "Runes 6d6 HP when read (adjacent no save, 10' Ref half)",
  "Eyebite": "R$RS' 1 target/rd with 4/9/10+ HD Fort save or comatose $L10 min/panicked d4 rd and shaken 10 min/sickened 10 min for $L rd",
  "Fabricate": "Create $L10' cube ($L' mineral cube) of finished items from raw materials",
  "Faerie Fire": "R$RL' Creatures in 5' radius glow for $L min",
  "False Life": "Self +1d10+$Lmin10 temporary HP for $L hr",
  "False Vision": "Scrying in touched 40' radius sees illusion for $L hr",
  "Fear": "R30' cone Creatures flee for $L rd (Will shaken 1 rd)",
  "Feather Fall": "R$RS' $L targets Will save or fall 60' for $L rd",
  "Feeblemind": "R$RM' Target Will save (arcane -4) or Int/Cha permanently drop to 1",
  "Find The Path": "Know most direct route to location for $L10 min",
  "Find Traps": "Self +10 Perception to notice traps w/in 10' for $L min",
  "Finger Of Death": "R$RS' Target $L10 HP (Fort 3d6+$L)",
  "Fire Seeds": "4 acorn grenades ${Math.min(lvl,20)}d4 total/8 berry bombs 1d8+$L (Ref half) that detonate on command for $L10 min",
  "Fire Shield": "Cold/hot flames enveloping self do d6+$Lmin15 HP upon foe hit, take half HP from heat/cold attacks (Ref no HP) for $L rd",
  "Fire Storm": "R$RM' $L2 10' cubes do ${Lmin20}d6 HP to targets, burn for 4d6/rd (Ref half and no burn)",
  "Fire Trap": "Warded object 1d4+$Lmin20 HP (Ref half) w/in 5' when opened",
  "Fireball": "R$RL' ${Lmin10}d6 HP (Ref half) in 20' radius",
  "Flame Arrow": "R$RS' 50 projectiles +1d6 HP for $L10 min",
  "Flame Blade": "Touch 1d8+${Math.min(Math.floor(lvl/2),10)} HP for $L min",
  "Flame Strike": "R$RM' 10' radius x 40' high ${Lmin15}d6 HP (Ref half)",
  "Flaming Sphere": "R$RM' 5' diameter sphere 3d6 HP (Ref negate) jump/move 30' for $L rd",
  "Flare": "R$RS' Target Fort save or dazzled 1 min",
  "Flesh To Stone": "Target Fort save or statue permanently",
  "Floating Disk": "R$RS' 3'-diameter x 1\" force disk follows, holds $L100 lbs at 3' for $L hr",
  "Fly": "Touched fly at 60' for $L min",
  "Fog Cloud": "R$RM' 20'-radius fog obscures vision for $L10 min",
  "Forbiddance": "R$RM' 60' cube bars planar travel, 6d6/12d6 HP on transit if align differs in 1/2 dimensions",
  "Forcecage": "R$RS' Traps targets in 20' cage/10' cube for $L rd",
  "Forceful Hand": "R$RM' 10' (AC 20, caster HP) hand cover (+4 AC), move 60', bull rush (CMB ${lvl + 9}, 2d6+12 HP) for $L rd",
  "Foresight": "Warnings provide +2 AC/Ref, no surprise/flat-footed for $L min",
  "Form Of The Dragon I": "Become Medium dragon (+4 Str/+2 Con/+4 AC/Fly 60'/Darkvision 60'/breath weapon once 6d8 HP (Ref half)/element resistance/bite 1d8 HP/claws 2x1d6 HP/wings 2x1d4 HP) for $L min",
  "Form Of The Dragon II": "Become Large dragon (+6 Str/+4 Con/+6 AC/Fly 90'/Darkvision 60'/breath weapon twice 8d8 HP (Ref half)/element resistance/bite 2d6 HP/claws 2x1d8 HP/wings 2x1d6 HP) for $L min",
  "Form Of The Dragon III": "Become Huge dragon (+10 Str/+8 Con/+8 AC/Fly 120'/Blindsense 60'/Darkvision 120'/breath weapon 1/d4 rd 12d8 HP (Ref half)/element immunity/bite 2d8 HP/claws 2x2d6 HP/wings 2x1d8 HP/tail 2d6 HP) for $L min",
  "Fox's Cunning": "Touched +4 Int for $L min",
  "Freedom": "R$RS' Target released from movement restrictions",
  "Freedom Of Movement": "R$RS' Target moves freely for $L10 min",
  "Freezing Sphere": "R$RL' Burst ${Lmin15}d6 HP in 40' radius (Ref half)",
  "Gaseous Form": "Touched insubstantial (DR 10/magic, immune poison/sneak/critical, unable to use spell components, fly 10') for $L2 min",
  "Gate": "5'-20' disk connects another plane for $L rd",
  "Geas/Quest": "R$RS' Target must complete task",
  "Gentle Repose": "Corpse Will save or preserved $L dy",
  "Ghost Sound": "R$RS' produce sound volume of $L4 humans (Will disbelieve) for $L rd",
  "Ghoul Touch": "Touched Fort save or paralyzed 1d6+2 rd and stench sickens 10' radius",
  "Giant Form I": "Become large giant (+6 Str/-2 Dex/+4 Con/+4 AC/low-light vision/form abilities) for $L min",
  "Giant Form II": "Become huge giant (+8 Str/-2 Dex/+6 Con/+6 AC/low-light vision/form abilities) for $L min",
  "Giant Vermin": "R$RS' ${lvl<10?3:lvl<14?4:lvl<18?6:lvl<20?8:12} centipedes/${lvl<20?1+Math.floor((lvl-6)/4):6} scorpions/${lvl<20?2+Math.floor((lvl-6)/4):8} spiders become giant and obey for $L min",
  "Glibness": "+20 Bluff, DC ${lvl+15} magical lie detection for $L10 min",
  "Glitterdust": "R$RM' Creatures in 10'-radius outlined and Will save or blind for $L rd",
  "Globe Of Invulnerability": "R10' Bars spell effects le 4th level for $L rd",
  "Glyph Of Warding": "Proscribed creatures passing $L5 sq' area trigger ${1+Math.max(Math.floor(lvl/2),5)}d8 blast or harmful spell le 3rd level",
  "Good Hope": "$L targets +2 attack/damage/saves and skill/ability checks for $L min",
  "Goodberry": "2d4 berries provide meal and heal 1 HP for $L dy",
  "Grasping Hand": "R$RM' 10' (AC 20, caster HP) hand cover (+4 AC), move 60', grapple (CMB ${lvl + 12}) for $L rd",
  "Grease": "R$RS' Object or 10' square slippery (Ref or fall) for $L min",
  "Greater Arcane Sight": "R120' See auras/spell abilities and know spell for $L min",
  "Greater Command": "R$RS' $L targets Will save each rd or approach/drop/fall/flee/halt for $L rd",
  "Greater Dispel Magic": "R$RM' d20+$L vs. 11+caster level cancels $Ldiv4 spells/effects or all w/in 20' radius",
  "Greater Glyph Of Warding": "Proscribed creatures passing $L5 sq' area trigger ${1+Math.max(Math.floor(lvl/2),10)}d8 blast or harmful spell le 6th level",
  "Greater Heroism": "Touched +4 attack/saves/skill checks, +$Lmin20 HP, immune fear for $L10 min",
  "Greater Invisibility": "Touched invisible for $L rd",
  "Greater Magic Fang": "R$RS' target natural weapon +${Math.min(Math.floor(lvl/4),4)} attack/damage for $L hr",
  "Greater Magic Weapon": "R$RS' target weapon +${Math.min(Math.floor(lvl/4),4)} attack/damage for $L hr",
  "Greater Planar Ally": "Purchase service from extraplanar creature le 18 HD",
  "Greater Planar Binding": "Extraplanar creature(s) le 18 HD Will save or trapped until escape (DC ${Math.floor(lvl/2)+15}+cha) or performs a task",
  "Greater Polymorph": "Willing target becomes animal/elemental/plant/dragon for $L min",
  "Greater Prying Eyes": "1d4+$L floating eyes (AC 18, 1 HP) with True Seeing scout 1 mi for $L hr",
  "Greater Restoration": "Touched remove magical/temporary/permanent ability harm, fatigue/exhaustion, negative levels, mental effects",
  "Greater Scrying": "Target special Will save or viewed, subject to spells for $L hr",
  "Greater Shadow Conjuration": "Mimics conjuration (creation/summoning) le 6th level, Will save 60% effect",
  "Greater Shadow Evocation": "Mimics evocation le 7th level, Will save 60% effect",
  "Greater Shout": "60' cone 10d6 HP, deafened 4d6 rd, stunned 1 rd (Will half damage/deafened only)",
  "Greater Spell Immunity": "Touched immune to $Ldiv4 spells le 8th level for $L10 min",
  "Greater Teleport": "Transport you, $Ldiv3 others anywhere w/no error chance",
  "Guards And Wards": "Multiple magic effects protect $L200' sq area for $L2 hr",
  "Guidance": "Touched +1 next attack/save/skill check for 1 min",
  "Gust Of Wind": "60' gust affects medium/smaller creatures",
  "Hallow": "40' radius warded against evil, bars undead creation, evokes boon spell",
  "Hallucinatory Terrain": "R$RL' ${L} 30' cube terrain illusion (Will disbelieve) for $L2 hr",
  "Halt Undead": "R$RM' 3 undead Will save or immobilized for $L rd",
  "Harm": "Touched ${Math.min(lvl*10,150)} HP (Will half)",
  "Haste": "R$RS' $L targets extra attack, +1 attack/AC/Ref, +30 move for $L rd",
  "Heal": "Touched heal ${Math.min(lvl*10,150)}, remove negative conditions",
  "Heal Mount": "Mount heal ${Math.min(lvl*10,150)}, remove negative conditions",
  "Heat Metal": "R$RS' Metal of $Ldiv2 creatures Will save or 0/1/2/2/2/1/0d4 HP for 7 rd",
  "Helping Hand": "R5 miles Ghostly hand leads target to you for 4 hr",
  "Heroes' Feast": "Food for $L creatures cures sickness/poison/disease, 1d8+${Math.min(Math.floor(lvl/2),10)} temporary HP, +1 attack/Will, +4 saves vs. poison/fear for 12 hr",
  "Heroism": "Touched +2 attack/saves/skill checks for $L10 min",
  "Hide From Animals": "$L touched imperceptable to animals for $L10 min",
  "Hide From Undead": "$L touched imperceptable to undead for $L10 min",
  "Hideous Laughter": "R$RS' Target Will save or ROFL for $L rd",
  "Hold Animal": "R$RM' Target immobile until Will save/$L rd",
  "Hold Monster": "R$RM' Target immobile until Will save/$L rd",
  "Hold Person": "R$RM' Target immobile until Will save/$L rd",
  "Hold Portal": "R$RM' Door/gate/window locked, +5 DC to open for $L min",
  "Holy Aura": "$L creatures w/in 20' +4 AC/saves, SR 25 vs. evil spells, protected from possession, striking foes Fort save or blinded, for $L rd",
  "Holy Smite": "R$RM' Evil w/in 20'-radius burst ${Math.min(Math.floor(source/2),5)}d8 HP and blinded 1 rd, neutral half (Will half)",
  "Holy Sword": "Touched weapon +5 attack/damage, vs. evil +2d6 damage, +2 AC/saves, extra save vs. enchantment, bars contact for $L rd",
  "Holy Word": "Nongood creatures w/in 40' with equal/-1/-5/-10 HD Will save or deafened 1d4 rd/blinded 2d4 rd (save 1d4)/paralyzed 1d10 min (save 1 rd)/killed (save 3d6+$Lmin25 HP)",
  "Horrid Wilting": "R$RL' ${Lmin20}d6 HP (${Lmin20}d8 plants/water elementals) in 30' radius",
  "Hypnotic Pattern": "R$RM' 2d4+$Lmin10 HD of creatures fascinated for conc + 2 rd",
  "Hypnotism": "R$RS' 2d4 HD of creatures fascinated and suggestable for 2d4 rd",
  "Ice Storm": "R$RL' Hail in 40' cylinder 3d6 HP bludgeoning/2d6 HP cold, -4 Perception for $L rd",
  "Identify": "R60' cone info on magical auras, +10 Spellcraft for $L3 rd",
  "Illusory Script": "Unauthorized readers Will save or suggestion for $L dy",
  "Illusory Wall": "R$RS' Permanent illusionary 1'x10'x10' surface (Will disbelieve)",
  "Imbue With Spell Ability": "Touched with 2/4/5 HD can cast specified 1st/2x1st/2x1st+2nd level spells",
  "Implosion": "R$RS' 1 target/rd Fort save or $L10 HP for $Ldiv2 rd",
  "Imprisonment": "Target Will save or entombed",
  "Incendiary Cloud": "R$RM' 20' cylinder moves away 10', 6d6 HP (Ref half) for $L rd",
  "Inflict Critical Wounds": "Touched damage/heal undead 4d8+$Lmin20 (Will half)",
  "Inflict Light Wounds": "Touched damage/heal undead 1d8+$Lmin5 (Will half)",
  "Inflict Minor Wounds": "Touched 1 HP",
  "Inflict Moderate Wounds": "Touched damage/heal undead 2d8+$Lmin10 (Will half)",
  "Inflict Serious Wounds": "Touched damage/heal undead 3d8+$Lmin15 (Will half)",
  "Insanity": "R$RM' Target Will save or randomly normal/babble/d8+str to self/attack nearest permanently",
  "Insect Plague": "R$RL' ${Math.min(Math.floor(lvl/3),6)} wasp swarms attack for $L min",
  "Instant Summons": "Prepared object appears in your hand",
  "Interposing Hand": "R$RM' 10' (AC 20, caster HP) hand cover (+4 AC) for $L rd",
  "Invisibility": "Touched invisible for $L min/until attacks",
  "Invisibility Purge": "R$L5' Invisible becomes visible for $L min",
  "Invisibility Sphere": "R10' All in range invisible for $L min/until attacks/leave area",
  "Iron Body": "Become iron (+6 Str/-6 Dex, half speed, 35% arcane failure, -6 skill, DR 15/adamantine, half damage acid/fire, immune other attacks/effects) for $L min",
  "Ironwood": "Make a wood object as strong as steel",
  "Irresistible Dance": "Touched dance (-4 AC, -10 Ref) for d4+1 rd (Will 1 rd)",
  "Jump": "Touched +${lvl<5?10:lvl<9?20:30} jump Acrobatics for $L min",
  "Keen Edge": "R$RS' Target weapon double threat range for $L10 min",
  "Knock": "R$RM' +${lvl+10} check to open stuck/barred/locked/magically held door/chest/shackle",
  "Know Direction": "You discern north",
  "Legend Lore": "Info about target person/place/object",
  "Lesser Confusion": "R$RS' Target Will save or randomly normal/babble/d8+str to self/attack nearest for 1 rd",
  "Lesser Geas": "R$RS' Target le 7 HD Will save or must complete task",
  "Lesser Globe Of Invulnerability": "Bars spell effects le 3rd level in 10' radius for $L rd",
  "Lesser Planar Ally": "Purchase service from extraplanar creature le 6 HD",
  "Lesser Planar Binding": "Extraplanar creature le 6 HD Will save or trapped until escape (DC ${Math.floor(lvl/2)+15}+cha) or performs a task",
  "Lesser Restoration": "Touched remove 1 magical/1d4 temporary ability harm, fatigue/exhaustion, 1 negative level",
  "Levitate": "R$RS' Move willing target up/down 20' for $L min",
  "Light": "Touched gives torchlight for $L10 min",
  "Lightning Bolt": "120' bolt ${Lmin10}d6 HP",
  "Limited Wish": "Alter reality, with limits",
  "Liveoak": "Touched oak becomes treant guardian for $L dy",
  "Locate Creature": "R$RL' Sense direction of creature/kind for $L10 min",
  "Locate Object": "R$RL' Sense direction of object/type for $L min",
  "Longstrider": "Self +10 speed for $L hr",
  "Lullaby": "R$RM' Targets in 10' radius -5 Perception/-2 Will saves vs. sleep for conc + $L rd",
  "Mage Armor": "Touched +4 AC for $L hr",
  "Mage Hand": "R$RS' Move target le 5 lb 15'",
  "Mage's Disjunction": "R$RS' 40' radius dispelled, magic items Will save or inert for $L min, $L% chance to destroy antimagic field",
  "Mage's Faithful Hound": "R$RS' Invisible dog barks at intruders w/in 30', bites (+10 2d6+3) w/in 5' for $L hr",
  "Mage's Lucubration": "Recalls spell le 5th level from past day",
  "Mage's Magnificent Mansion": "R$RS' Door to extradimensional mansion for $L2 hr",
  "Mage's Private Sanctum": "Prevents outside view/scry/hear of ${L} 30' cubes for 1 dy",
  "Mage's Sword": "R$RS' Unattended force blade attacks (+${lvl+3}+abil 4d6+3x2@19) for $L rd",
  "Magic Aura": "Alters aura of target object le $L5 lb for $L dy",
  "Magic Circle Against Chaos": "10' radius from touched +2 AC/+2 saves/extra save vs. mental control/no contact vs. chaotic creatures for $L10 min",
  "Magic Circle Against Evil": "10' radius from touched +2 AC/+2 saves/extra save vs. mental control/no contact vs. evil creatures for $L10 min",
  "Magic Circle Against Good": "10' radius from touched +2 AC/+2 saves/extra save vs. mental control/no contact vs. good creatures for $L10 min",
  "Magic Circle Against Law": "10' radius from touched +2 AC/+2 saves/extra save vs. mental control/no contact vs. lawful creatures for $L10 min",
  "Magic Fang": "Touched natural weapon +1 attack/damage for $L min",
  "Magic Jar": "R$RM' Target Will save or possessed for $L hr",
  "Magic Missile": "R$RM' ${Math.min(Math.floor((lvl+1)/2),5)} missles 1d4+1 HP",
  "Magic Mouth": "R$RS' Mouth speaks 25 words upon trigger w/in $L15'",
  "Magic Stone": "3 touched stones +1 attack/1d6+1 HP (2d6+2 vs. undead) for 30 min",
  "Magic Vestment": "Touched armor/shield/clothing +${Math.min(Math.floor(lvl/4),5)} AC for $L hr",
  "Magic Weapon": "Touched weapon +1 attack/damage for $L min",
  "Major Creation": "Create $L' cu plant/mineral object for $L2 hr",
  "Major Image": "R$RL' ${lvl+4} 10' cu image w/sound/smell/thermal (Will disbelieve) for conc + 3 rd",
  "Make Whole": "R$RS' Repairs ${Lmin5}d6 damage to $L' cu object",
  "Mark Of Justice": "Touched permanent -6 ability, -4 attack/saves/checks, or 50% chance/rd of losing action upon trigger",
  "Mass Bear's Endurance": "R$RS' $L targets +4 Con for $L min",
  "Mass Bull's Strength": "R$RS' $L targets +4 Str for $L min",
  "Mass Cat's Grace": "R$RS' $L targets +4 Dex for $L min",
  "Mass Charm Monster": "R$RS' $L2 HD targets Will save or treats you as trusted friend for $L dy",
  "Mass Cure Critical Wounds": "R$RS' $L targets heal/damage undead 4d8+$Lmin40 (Will half)",
  "Mass Cure Light Wounds": "R$RS' $L targets heal/damage undead 1d8+$Lmin25 (Will half)",
  "Mass Cure Moderate Wounds": "R$RS' $L targets heal/damage undead 2d8+$Lmin30 (Will half)",
  "Mass Cure Serious Wounds": "R$RS' $L targets heal/damage undead 3d8+$Lmin35 (Will half)",
  "Mass Eagle's Splendor": "R$RS' $L targets +4 Cha for $L min",
  "Mass Enlarge Person": "R$RS' $L target humanoid Fort save or double size (+2 Str/-2 Dex/-1 attack/-1 AC) for $L min",
  "Mass Fox's Cunning": "R$RS' $L targets +4 Int for $L min",
  "Mass Heal": "R$RS' $L targets heal ${Math.min(lvl*10,150)}, remove negative conditions",
  "Mass Hold Monster": "R$RM' Targets in 30' radius immobile until Will save/$L rd",
  "Mass Hold Person": "R$RM' Targets in 30' radius immobile until Will save/$L rd",
  "Mass Inflict Critical Wounds": "R$RS' $L targets damage/heal undead 4d8+$Lmin40 (Will half)",
  "Mass Inflict Light Wounds": "R$RS' $L targets damage/heal undead 1d8+$Lmin25 (Will half)",
  "Mass Inflict Moderate Wounds": "R$RS' $L targets damage/heal undead 2d8+$Lmin30 (Will half)",
  "Mass Inflict Serious Wounds": "R$RS' $L targets damage/heal undead 3d8+$Lmin35 (Will half)",
  "Mass Invisibility": "R$RL' Targets in 90' radius invisible for $L min/until attacks",
  "Mass Owl's Wisdom": "R$RS' $L targets +4 Wis for $L min",
  "Mass Reduce Person": "R$RS' $L target humanoid Fort save or half size (-2 Str/+2 Dex/+1 attack/+1 AC) for $L min",
  "Mass Suggestion": "R$RM' $L targets Will save or follow reasonable suggestion",
  "Maze": "R$RS' Target in extradimensional maze for 10 min/until DC 20 Int check",
  "Meld Into Stone": "Self pass into stone for $L10 min",
  "Mending": "R10' Repairs 1d4 HP to $L-lb object",
  "Message": "R$RM' Target DC 25 Perception for $L10-min whispered dialogue",
  "Meteor Swarm": "R$RL' 4 spheres 6d6 HP fire 40' radius (Ref half)/ranged touch 2d6 HP bludgeoning",
  "Mind Blank": "R$RS' Target immune divination/+8 vs. mental for 1 dy",
  "Mind Fog": "20' fog cylinder -10 Wis/Will checks",
  "Minor Creation": "Create a $L' cu plant object lasting $L hr",
  "Minor Image": "R$RL' ${lvl+4} 10' cu image w/noise (Will disbelieve) for conc + 2 rd",
  "Miracle": "Requests deity's intercession",
  "Mirage Arcana": "R$RL' ${L} 20' cube terrain/structure illusion (Will disbelieve) for $L hr",
  "Mirror Image": "1d4+${Math.min(Math.floor(lvl/3),8)} self decoys mislead attacks for $L min",
  "Misdirection": "R$RS' Divinations upon target redirected for $L hr",
  "Mislead": "R$RS' Self invisible $L rd, false double (Will disbelieve) conc + 3 rd",
  "Mnemonic Enhancer": "Know +3 spell levels or retain just-cast spell le 3rd level for 1 dy",
  "Modify Memory": "Target Will save or change 5 min of memory",
  "Moment Of Prescience": "Self +$Lmin25 attack/check/save once w/in $L hr",
  "Mount": "R$RS' Summons riding horse for $L2 hr",
  "Move Earth": "R$RL' Slowly digs 7500' cu dirt",
  "Neutralize Poison": "Touched neutralized $L10 min/immunized/detoxified",
  "Nightmare": "Target Will save or 1d10 HP and fatigue",
  "Nondetection": "Touched DC ${lvl+11}/${lvl+15} resistance to divination for $L hr",
  "Obscure Object": "Touched immune to divination for 8 hr",
  "Obscuring Mist": "20'-radius fog obscures vision for $L min",
  "Open/Close": "R$RS' Target le 30 lb opens/closes",
  "Order's Wrath": "R$RM' Chaotic w/in 30' cube ${Math.min(Math.floor(source/2),5)}d8 HP and dazed 1 rd, neutral half (Will half)",
  "Overland Flight": "Self fly 40', +$Ldiv2 Fly for $L hr",
  "Owl's Wisdom": "Touched +4 Wis for $L min",
  "Pass Without Trace": "$L touched leave no tracks/scent for $L hr",
  "Passwall": "8'x5'x${Math.min(10+5*Math.floor((lvl-9)/3),25)}' passage through wood/stone/plaster lasts $L hr",
  "Permanency": "Makes certain spells permanent",
  "Permanent Image": "R$RL' ${lvl+4} 10' cu image w/sound/smell/thermal (Will disbelieve)",
  "Persistent Image": "R$RL' ${lvl+4} 10' cu image w/sound/smell/thermal (Will disbelieve) for $L min",
  "Phantasmal Killer": "R$RM' Target Will save or fears create creature, touch kills (Fort 3d6 HP)",
  "Phantom Steed": "Create mount (${lvl+7} HP, AC 18, MV ${Math.min(Math.floor(lvl/2)*20,100)}) for target for $L hr",
  "Phantom Trap": "Touched object appears trapped",
  "Phase Door": "Allow passage through 8'x5'x${Math.min(10+5*Math.floor((lvl-9)/3),25)}' wood/stone/plaster $Ldiv2 times",
  "Planar Ally": "Purchase service from extraplanar creature le 12 HD",
  "Planar Binding": "Extraplanar creature(s) le 12 HD Will save or trapped until escape (DC ${Math.floor(lvl/2)+15}+cha) or performs a task",
  "Plane Shift": "1 target (Will negate)/8 willing move to another plane",
  "Plant Growth": "$RL' vegetation becomes dense or 1/2 mi radius increases productivity",
  "Plant Shape I": "Become small (+2 Con/+2 AC) or medium (+2 Str/+2 Con/+2 AC) plant creature for $L min",
  "Plant Shape II": "Become large (+4 Str/+2 Con/+4 AC) plant creature for $L min",
  "Plant Shape III": "Become huge (+8 Str/-2 Dex/+4 Con/+6 AC) plant creature for $L min",
  "Poison": "Touched Fort save or 1d3 Con/rd for 6 rd",
  "Polar Ray": "R$RM' Ranged touch ${Lmin25}d6 HP/1d4 Dex",
  "Polymorph": "Willing target becomes animal/elemental for $L min",
  "Polymorph Any Object": "Target Fort save or become something else",
  "Power Word Blind": "R$RS' Target w/ 50/100/200 HP blinded for ever/1d4+1 min/1d4+1 rd",
  "Power Word Kill": "R$RS' Kills one creature le 100 HP",
  "Power Word Stun": "R$RS' Target w/ 40/100/150 HP stunned for 4d4/2d4/1d4 rd",
  "Prayer": "Allies w/in 40' +1 attack/damage/save/skill, foes -1 for $L rd",
  "Prestidigitation": "R10' Perform minor tricks for 1 hr",
  "Prismatic Sphere": "R$RS' 10' sphere blocks attacks for $L10 min",
  "Prismatic Spray": "R60' cone Blinds le 8 HD 2d4 rd, other effects",
  "Prismatic Wall": "R$RS' $L4'x$L2' wall blocks attacks for $L10 min",
  "Produce Flame": "Torch flame 1d6+$Lmin5 HP for $L min",
  "Programmed Image": "R$RL' ${lvl+4} 10' cu image w/sound/smell/thermal (Will disbelieve) for $L rd when triggered",
  "Project Image": "R$RM' See/cast through illusory double for $L rd",
  "Protection From Arrows": "Target DR 10/magic vs. ranged for $L hr/${Math.min(lvl*10,100)} HP",
  "Protection From Chaos": "Touched +2 AC/+2 saves/extra save vs. mental control/no contact by chaotic creatures for $L min",
  "Protection From Energy": "Touched ignores up to ${Math.min(lvl*12,120)} HP from specified energy for $L10 min",
  "Protection From Evil": "Touched +2 AC/+2 saves/extra save vs. mental control/no contact by evil creatures for $L min",
  "Protection From Good": "Touched +2 AC/+2 saves/extra save vs. mental control/no contact by good creatures for $L min",
  "Protection From Law": "Touched +2 AC/+2 saves/extra save vs. mental control/no contact by lawful creatures for $L min",
  "Protection From Spells": "+8 spell saves for $L10 min",
  "Prying Eyes": "1d4+$L floating eyes (AC 18, 1 HP) scout 1 mi for $L hr",
  "Purify Food And Drink": "R10' Make $L' cu food/water safe",
  "Pyrotechnics": "R$RL' Fire becomes fireworks (120' Will save or blinded 1d4+1 rd) or choking smoke (20' Fort save or -4 Str/Dex d4+1 rd)",
  "Quench": "R$RM' Extinguish fire/dispel fire magic/${Lmin10}d6 HP to fire creatures in $L 20' cu",
  "Rage": "R$RM' $Ldiv3 willing targets +2 Str/Con, +1 Will, -2 AC for conc + $L rd",
  "Rainbow Pattern": "R$RM' 24 HD creatures in 20' radius Will save or facinated for conc + $L rd",
  "Raise Dead": "Restores life to touched corpse dead le $L dy",
  "Ray Of Enfeeblement": "R$RS' Ranged touch 1d6+${Math.min(Math.floor(lvl/2),5)} Str (Fort half)",
  "Ray Of Exhaustion": "R$RS' Ranged touch causes exhaustion for $L min (Save fatigued)",
  "Ray Of Frost": "R$RS' Ranged touch 1d3 HP",
  "Read Magic": "Self read magical writing",
  "Reduce Animal": "Touched willing animal half size (-2 Str/+2 Dex/+1 attack/+1 AC) for $L hr",
  "Reduce Person": "R$RS' Target humanoid Fort save or half size (-2 Str/+2 Dex/+1 attack/+1 AC) for $L min",
  "Refuge": "Breaking trigger transports you/target to other's location",
  "Regenerate": "Touched regrow maims, heal 4d8+$Lmin35 HP, rid fatigue/exhaustion",
  "Reincarnate": "Restore target dead le 1 week to new body",
  "Remove Blindness/Deafness": "Touched cured of blindness or deafness",
  "Remove Curse": "Dispels all curses from touched",
  "Remove Disease": "Cures all diseases affecting touched",
  "Remove Fear": "R$RS' ${Math.floor((lvl+3)/4)} targets +4 vs. fear, existing fear suppressed for 10 min",
  "Remove Paralysis": "R$RS' Frees one target from paralysis/slow, 2/3/4 targets extra save at +4/+2/+2",
  "Repel Metal Or Stone": "Repels 60' line of unanchored metal/stone for $L rd",
  "Repel Vermin": "10' radius bars vermin le $Ldiv3 HD, 2d6 HP to others w/Will save for $L10 min",
  "Repel Wood": "Repels 60' line of unanchored wood for $L min",
  "Repulsion": "Creatures Will save or stay $L10' away for $L rd",
  "Resilient Sphere": "R$RS' Impassible/immobile $L'-diameter sphere surrounds target for $L min",
  "Resist Energy": "Touched DR ${lvl>10?30:lvl>6?20:10} from specified energy for $L10 min",
  "Resistance": "Touched +1 saves for 1 min",
  "Restoration": "Touched remove magical/temporary/1 permanent ability harm, fatigue/exhaustion, 1 negative level",
  "Resurrection": "Fully restore target dead $L10 years w/1 negative level",
  "Reverse Gravity": "Objects in $L 10' cu fall upward for $L rd",
  "Righteous Might": "Self double size (+4 Str/+4 Con/-2 Dex/-1 attack/-1 AC) and DR ${lvl>14?10:5}/align for $L rd",
  "Rope Trick": "Rope to extradimensional space for 8 creatures for $L hr",
  "Rusting Grasp": "Touch corrodes 3' radius",
  "Sanctuary": "Touched foes Will save to attack for $L rd/until attacks",
  "Scare": "R$RS' $Ldiv3 targets le 5 HD flee for 1d4 rd (Will shaken 1 rd)",
  "Scintillating Pattern": "R$RS' $Lmin20 HD creatures in 20' radius le 6/12/20 HD unconscious 1d4 rd/stunned 1d4 rd/confused 1d4 rd",
  "Scorching Ray": "${lvl>10?3:lvl>6?2:1} $RS' rays ranged touch 4d6 HP",
  "Screen": "Illusion hides $L x 30' cu from vision and scrying (Will disbelieve) for 1 dy",
  "Scrying": "Target special Will save or viewed for $L min",
  "Sculpt Sound": "R$RS' $L targets Will save or sounds changed for $L hr",
  "Searing Light": "R$RM' Range touch ${Math.min(Math.floor(lvl/2),5)}d8 HP, undead ${Lmin10}d6, object ${Math.min(Math.floor(lvl/2),5)}d6",
  "Secret Chest": "$L' cu ethereal chest can be recalled at will for 60 dy",
  "Secret Page": "Hide content of touched page permanently",
  "Secure Shelter": "R$RS' 20'x20' cottage lasts $L2 hr",
  "See Invisibility": "Reveals invisible creatures/objects for $L10 min",
  "Seeming": "R$RS' $Ldiv2 targets appearance change/+10 disguise for 12 hr",
  "Sending": "25-word exchange with target",
  "Sepia Snake Sigil": "Target reader Ref save or immobile 1d4+$L dy",
  "Sequester": "Willing touched invisible/unscryable/comatose for $L dy",
  "Shades": "Mimics conjuration (creation/summoning) le 8th level (Will 80% effect)",
  "Shadow Conjuration": "Mimics conjuration (creation/summoning) le 3rd level (Will 20% effect)",
  "Shadow Evocation": "Mimics evocation le 4th level (Will 20% effect)",
  "Shadow Walk": "Travel quickly via Plane of Shadow for $L hr",
  "Shambler": "R$RM' 1d4+2 advanced shambling mounds fight for 7 dy/guard for 7 mo",
  "Shapechange": "Become different animal 1/rd for $L10 min",
  "Shatter": "R$RS' Breakables in 5' radius Will save or shatter, or target ${Lmin10}d6 HP (Fort half)",
  "Shield": "Self +4 AC, block magic missle for $L min",
  "Shield Of Faith": "Touched +${Math.min(2+Math.floor(lvl/6),5)} AC for $L min",
  "Shield Of Law": "$L creatures w/in 20' radius +4 AC/saves, +25 vs chaotic spells, immune chaotic mental control, chaotic hit Will save or slowed for $L rd",
  "Shield Other": "R$RS' target +1 AC/saves, half damage transferred to you for $L hr",
  "Shillelagh": "S/M/L staff +1 attack, 1d8+1/2d6+1/3d6+1 damage for $L min",
  "Shocking Grasp": "Touch ${Lmin5}d6 HP, +3 attack vs metal",
  "Shout": "R30' cone 5d6 HP, deafened 2d6 rd (Will half damage only)",
  "Shrink Item": "Touched $L2' cu object Will save or 1/16 size, becomes cloth for $L dy",
  "Silence": "R$RL' Bars sound in 20' radius for $L rd",
  "Silent Image": "R$RL' ${(lvl+4)*10}' cu image (Will disbelieve) for conc",
  "Simulacrum": "Create permanent double of creature w/half HP/levels",
  "Slay Living": "Touch attack 12d6+$L HP (Fort 3d6+$L)",
  "Sleep": "R$RM' 4 HD creatures in 10' radius Will save or sleep for $L min",
  "Sleet Storm": "R$RL' Blinding sleet in 40' area, creatures DC 10 Acrobatics to move for $L rd",
  "Slow": "R$RS' $L creatures single action per rd/-1 AC/attack/Ref/half speed for $L rd",
  "Snare": "Touched vine/thong/rope becomes permanent DC 23 trap",
  "Soften Earth And Stone": "R$RS' $L 10'x4' squares of wet earth/dry earth/natural stone becomes mud/sand/clay",
  "Solid Fog": "R$RM' 20'-radius fog obscures vision and half speed/-2 damage/attack for $L min",
  "Song Of Discord": "R$RM' Creatures in 20' radius 50% chance each rd to attack neighbor for $L rd",
  "Soul Bind": "Imprisons soul dead le $L rd to prevent resurrection",
  "Sound Burst": "R$RS' 10' radius 1d8 HP/Fort save or stunned",
  "Speak With Animals": "Self converse w/animals for $L min",
  "Speak With Dead": "R10' Corpse answer $Ldiv2 questions",
  "Speak With Plants": "Self converse w/plants for $L min",
  "Spectral Hand": "Self yield 1d4 HP to glowing hand to deliver touch attacks at +2 for $L min",
  "Spell Immunity": "Touched immune to $Ldiv4 spells le 4th level for $L10 min",
  "Spell Resistance": "Touched +${lvl+12} saves vs spells for $L min",
  "Spell Turning": "Self reflect onto caster 1d4+6 non-touch spell levels for $L10 min",
  "Spellstaff": "Store 1 spell in wooden quarterstaff",
  "Spider Climb": "Touched climb walls/ceilings for $L10 min",
  "Spike Growth": "R$RM' Spikes on vegetation in 20' sq 1d4 HP each 5' movement and Ref save or slowed 1 dy to half speed for $L hr",
  "Spike Stones": "R$RM' Spikes on stony group in 20' sq 1d8 HP each 5' movement and Ref save or slowed 1 dy to half speed for $L hr",
  "Spiritual Weapon": "R$RM' Force weapon (+BAB+Wis 1d8+${Math.min(Math.floor(lvl/3),5)}) attacks designated foes for $L rd",
  "Stabilize": "R$RS' Stabilize dying target",
  "Statue": "Touched become statue at will for $L hr",
  "Status": "Monitor condition/position of $Ldiv3 touched allies for $L hr",
  "Stinking Cloud": "R$RM' 20'-radius fog obscures vision, Fort save or 1d4+1 rd nausea (no attacks/spells) for $L rd",
  "Stone Shape": "Shape ${10+lvl}' cu of stone",
  "Stone Tell": "Self dialogue w/stone for $L min",
  "Stone To Flesh": "R$RM' Restore stoned creature (DC 15 Fort to survive) or make flesh 10'x3' stone cyclinder",
  "Stoneskin": "Touched DR 10/adamantine for ${Math.min(lvl*10,150)} HP/$L min",
  "Storm Of Vengeance": "R$RL' 360' radius storm deafen 1d4x10 min (Fort negates), then rain acid 1d6 HP, then 6 bolts lightning 10d6 (Ref half), then hail 5d6 HP, then dark 6 rd",
  "Suggestion": "R$RS' Target Will save or follow reasonable suggestion",
  "Summon Instrument": "Musical instrument appears for $L min",
  "Summon Monster I": "R$RS' 1 1st-level creature appears, fights foes for $L rd",
  "Summon Monster II": "R$RS' 1 2nd-/1d3 1st-level creature appears, fights foes for $L rd",
  "Summon Monster III": "R$RS' 1 3rd-/1d3 2nd-/1d4+1 1st-level creature appears, fights foes for $L rd",
  "Summon Monster IV": "R$RS' 1 4th-/1d3 3rd-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Monster V": "R$RS' 1 5th-/1d3 4th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Monster VI": "R$RS' 1 6th-/1d3 5th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Monster VII": "R$RS' 1 7th-/1d3 6th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Monster VIII": "R$RS' 1 8th-/1d3 7th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Monster IX": "R$RS' 1 9th-/1d3 8th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally I": "R$RS' 1 1st-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally II": "R$RS' 1 2nd-/1d3 1st-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally III": "R$RS' 1 3rd-/1d3 2nd-/1d4+1 1st-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally IV": "R$RS' 1 4th-/1d3 3rd-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally V": "R$RS' 1 5th-/1d3 4th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally VI": "R$RS' 1 6th-/1d3 5th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally VII": "R$RS' 1 7th-/1d3 6th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally VIII": "R$RS' 1 8th-/1d3 7th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Nature's Ally IX": "R$RS' 1 9th-/1d3 8th-/1d4+1 lower-level creature appears, fights foes for $L rd",
  "Summon Swarm": "R$RS' Swarm of bats/rats/spiders obey for conc + 2 rd",
  "Sunbeam": "60' beam blinds, 4d6 HP (undead ${Lmin20}d6) (Ref unblind/half) 1/rd for ${Math.min(Math.floor(lvl/30),6)} rd",
  "Sunburst": "R$RL' 80' radius blinds, 6d6 HP (undead ${Lmin25}d6) (Ref unblind/half)",
  "Symbol Of Death": "R60' Rune kills 150 HP of creatures (Fort negate) when triggered",
  "Symbol Of Fear": "R60' Rune panics creatures (Will negate) for $L rd when triggered",
  "Symbol Of Insanity": "R60' Rune makes creatures insane (Will negate) permanently when triggered",
  "Symbol Of Pain": "R60' Rune causes pain (-4 attack/skill/ability, Fort negate) when triggered for $L10 min",
  "Symbol Of Persuasion": "R60' Rune charms creatures (Will negate) for $L hrs when triggered for $L10 min",
  "Symbol Of Sleep": "R60' Rune sleeps creatures (Will negate) le 10 HD for 3d6x10 min when triggered for $L10 min",
  "Symbol Of Stunning": "R60' Rune stuns creatures (Will negate) for 1d6 rd when triggered",
  "Symbol Of Weakness": "R60' Rune weakens creatures (3d6 Str, Fort negate) permanently when triggered for $L10 min",
  "Sympathetic Vibration": "Touched structure 2d10 HP/rd for $L rd",
  "Sympathy": "Named kind/alignment creatures Will save or drawn to $L10' cube for $L2 hr",
  "Telekinesis": "R$RL' Move ${Math.min(lvl*25,375)} lb 20' for $L rd, combat maneuver (CMB $L) $L rd, or hurl ${Math.min(lvl,15)} objects ${Math.min(lvl*25,375)} lbs total (Will negate)",
  "Telekinetic Sphere": "R$RS' Impassible $L'-diameter sphere surrounds target, move 30' to $RM' away for $L min",
  "Telepathic Bond": "R$RS' Self share thoughts w/$Ldiv3 allies for $L10 min",
  "Teleport": "Transport you, $Ldiv3 others $L100 mi w/some error chance",
  "Teleport Object": "Transport touched object $L100 mi w/some error chance",
  "Teleportation Circle": "Transport creatures in 5' radius anywhere w/no error chance for $L10 min",
  "Temporal Stasis": "Touched Fort save or in permanent stasis",
  "Time Stop": "All others halt, invulnerable for 1d4+1 rd",
  "Tiny Hut": "20' sphere resists elements for $L2 hr",
  "Tongues": "Touched communicate in any language for $L10 min",
  "Touch Of Fatigue": "Touch attack fatigues target for $L rd",
  "Touch Of Idiocy": "Touch attack 1d6 Int/Wis/Cha for $L10 min",
  "Transformation": "Self +4 Str/Dex/Con/AC, +5 Fort, martial prof, no spells for $L rd",
  "Transmute Metal To Wood": "R$RL' Metal 40' radius becomes wood (-2 attack/damage/AC)",
  "Transmute Mud To Rock": "R$RM' $L2 10' mud cubes become rock",
  "Transmute Rock To Mud": "R$RM' $L2 10' natural rock cubes become mud",
  "Transport Via Plants": "Self and $Ldiv3 willing targets teleport via like plants",
  "Trap The Soul": "R$RS' Target Will save or imprisoned in gem",
  "Tree Shape": "Become tree for $L hr",
  "Tree Stride": "Teleport 3000' via like trees",
  "True Resurrection": "Fully restore target dead $L10 yr",
  "True Seeing": "Touched sees through 120' darkness/illusion/invisible for $L min",
  "True Strike": "Self +20 next attack",
  "Undeath To Death": "R$RM' ${Lmin20}d4 HD of creatures le 8 HD w/in 40' Will save or destroyed",
  "Undetectable Alignment": "R$RS' Target Will save or alignment concealed for 1 dy",
  "Unhallow": "40' radius warded against good, evokes bane spell",
  "Unholy Aura": "$L creatures w/in 20' +4 AC/saves, SR 25 vs. good spells, protected from possession, good hit Fort save or 1d6 Str, for $L rd",
  "Unholy Blight": "R$RM' Good w/in 20'-radius burst ${Math.min(Math.floor(source/2),5)}d8 HP and sickened 1d4 rd, neutral half (Will half)",
  "Unseen Servant": "R$RS' Invisible servant obey for $L hr",
  "Vampiric Touch": "Touch attack ${Math.min(Math.floor(lvl/2),10)} HP, gain half as temporary HP for 1 hr",
  "Veil": "R$RL' Targets in 30' radius Will save or appear as other creatures for conc + $L hr",
  "Ventriloquism": "R$RS' Self voice moves for $L min",
  "Virtue": "Touched +1 HP for 1 min",
  "Vision": "Info about target person/place/object",
  "Wail Of The Banshee": "R$RS' $L targets w/in 40' Fort save or $L10 HP",
  "Wall Of Fire": "R$RM' $L20' wall 2d4 HP w/in 10', 1d4 HP w/in 20', 2d6 HP transit (undead double) for conc + $L rd",
  "Wall Of Force": "R$RS' Impassible/immobile $L x 10' sq wall $L rd",
  "Wall Of Ice": "R$RM' $L x 10' x $L\" ice wall or ${lvl+3}' hemisphere for $L min",
  "Wall Of Iron": "R$RM' $L x 5' $Ldiv4\"-thick permanent iron wall",
  "Wall Of Stone": "R$RM' $L x 5' $Ldiv4\"-thick permanent stone wall",
  "Wall Of Thorns": "R$RM' $L x 10' cube thorns (25-AC) HP/rd to transiters for $L10 min",
  "Warp Wood": "R$RS' $L wooden objects Will save or warped",
  "Water Breathing": "Touched breathe underwater for $L2 hrs total",
  "Water Walk": "$L touched tread on liquid as if solid for $L10 min",
  "Waves Of Exhaustion": "60' cone exhausted",
  "Waves Of Fatigue": "30' cone fatigued",
  "Web": "R$RM' 20'-radius webs grapple (Ref negate), burn for 2d4 HP for $L10 min",
  "Weird": "R$RM' Targets in 30' radius Will save or fears create creature, touch kills (Fort 3d6 HP/1d4 Str/stun 1 rd)",
  "Whirlwind": "R$RL' 10'-radius wind 1d8 HP/rd for $L rd (Ref negate)",
  "Whispering Wind": "Send 25-word message $L mi to 10' area",
  "Wind Walk": "Self + $Ldiv3 touched vaporize and move 60 mph for $L hr",
  "Wind Wall": "R$RM' $L10'x5' curtain of air scatters objects, deflects arrows/bolts for $L rd",
  "Wish": "Alter reality, with few limits",
  "Wood Shape": "Shape ${10+lvl}' cu of wood",
  "Word Of Chaos": "Nonchaotic creatures w/in 40' with equal/-1/-5/-10 HD Will save or deafened 1d4 rd/stunned 1 rd/confused 1d10 min (save 1 rd)/killed (save 3d6+$Lmin25 HP)",
  "Word Of Recall": "Self + $Ldiv3 willing targets return to designated place",
  "Zone Of Silence": "No sound escapes 5' radius around self for $L hr",
  "Zone Of Truth": "R$RS' Creatures w/in 20' radius Will save or cannot lie for $L min"
};
SRD35SpellDescriptions.abbreviations = {
  "BarkskinAC": "2 + (source < 6 ? 0 : Math.min(Math.floor((source - 3)/ 3), 3))",
  "L": "lvl",
  "L2": "lvl * 2",
  "L3": "lvl * 3",
  "L4": "lvl * 4",
  "L5": "lvl * 5",
  "L10": "lvl * 10",
  "L15": "lvl * 15",
  "L20": "lvl * 20",
  "L40": "lvl * 40",
  "L100": "lvl * 100",
  "L200": "lvl * 200",
  "Ldiv2": "Math.floor(lvl/2)",
  "Ldiv3": "Math.floor(lvl/3)",
  "Ldiv4": "Math.floor(lvl/4)",
  "Lmin5": "Math.min(source, 5)",
  "Lmin10": "Math.min(source, 10)",
  "Lmin15": "Math.min(source, 15)",
  "Lmin20": "Math.min(source, 20)",
  "Lmin25": "Math.min(source, 25)",
  "Lmin30": "Math.min(source, 30)",
  "Lmin35": "Math.min(source, 35)",
  "Lmin40": "Math.min(source, 40)",
  "RL": "400 + 40 * source",
  "RM": "100 + 10 * source",
  "RS": "25 + 5 * Math.floor(source / 2)"
};
/* Replaces spell names with longer descriptions on the character sheet. */
SRD35SpellDescriptions.spellRules = function(rules, spells, descriptions) {
  if(spells == null) {
    spells = ScribeUtils.getKeys(rules.choices.spells);
  }
  if(descriptions == null) {
    descriptions = SRD35SpellDescriptions.descriptions;
  }
  rules.defineRule('casterLevels.AS', 'levels.Assassin', '=', null);
  rules.defineRule('casterLevels.B', 'levels.Bard', '=', null);
  rules.defineRule('casterLevels.BL', 'levels.Blackguard', '=', null);
  rules.defineRule('casterLevels.C', 'levels.Cleric', '=', null);
  rules.defineRule('casterLevels.D', 'levels.Druid', '=', null);
  rules.defineRule('casterLevels.Dom', 'levels.Cleric', '=', null);
  rules.defineRule('casterLevels.Dom', 'levels.Druid', '=', null);
  rules.defineRule('casterLevels.Dom', 'levels.Legate', '=', null);
  rules.defineRule('casterLevels.P', 'levels.Paladin', '=', null);
  rules.defineRule('casterLevels.R', 'levels.Ranger', '=', null);
  rules.defineRule('casterLevels.W', 'levels.Sorcerer', '=', null);
  rules.defineRule('casterLevels.W', 'levels.Wizard', '=', null);
  rules.defineRule('casterLevels.L', 'levels.Legate', '=', null);
  for(var i = 0; i < spells.length; i++) {
    var spell = spells[i];
    var matchInfo = spell.match(/^([^\(]+)\(([A-Za-z]+)(\d+)\s*\w*\)$/);
    if(matchInfo == null) {
      alert("Bad format for spell " + spell);
      continue;
    }
    var abbr = matchInfo[2];
    var level = matchInfo[3];
    var name = matchInfo[1];
    var description = descriptions[name];
    if(description == null) {
      alert("No description for spell " + name);
      continue;
    }
    if(abbr.length > 2) {
      abbr = "Dom"; // Assume domain spell
    }
    var inserts = description.match(/\$(\w+|{[^}]+})/g);
    if(inserts != null) {
      for(var index = 1; index <= inserts.length; index++) {
        var insert = inserts[index - 1];
        var expr = insert[1] == "{" ?
            insert.substring(2, insert.length - 1) : insert.substring(1);
        if(SRD35SpellDescriptions.abbreviations[expr] != null) {
          expr = SRD35SpellDescriptions.abbreviations[expr];
        }
        expr = expr.replace(/lvl/g, "source");
        rules.defineRule
          ("spells." + spell + "." + index, "casterLevels." + abbr, "=", expr);
        description = description.replace(insert, "%" + index);
      }
    }
    rules.defineChoice("notes", "spells." + spell + ":" + description);
  }
};
